# Generated by Django 5.2.10 on 2026-01-30 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0003_alter_publication_conference_date_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, help_text="Volumen izdanja (npr. '1', 'Special')", max_length=20, verbose_name='Volumen')),
                ('issue_number', models.CharField(blank=True, help_text="Broj izdanja (npr. '1', 'Supplement')", max_length=20, verbose_name='Broj izdanja')),
                ('year', models.PositiveIntegerField(help_text='Godina izdanja', verbose_name='Godina')),
                ('title', models.CharField(blank=True, help_text='Opcioni naslov izdanja', max_length=500, verbose_name='Naslov')),
                ('cover_image', models.ImageField(blank=True, help_text='Naslovna slika izdanja', null=True, upload_to='issues/covers/', verbose_name='Naslovna slika')),
                ('publication_date', models.DateField(blank=True, help_text='Datum objave izdanja', null=True, verbose_name='Datum objave')),
                ('status', models.CharField(choices=[('DRAFT', 'Nacrt'), ('SCHEDULED', 'Zakazano'), ('PUBLISHED', 'Objavljeno'), ('ARCHIVE', 'Arhivirano')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('proceedings_title', models.CharField(blank=True, help_text='Naslov zbornika (ako se razlikuje od naslova publikacije)', max_length=500, verbose_name='Naslov zbornika')),
                ('proceedings_publisher_name', models.CharField(blank=True, help_text='Naziv izdavača zbornika', max_length=255, verbose_name='Naziv izdavača zbornika')),
                ('proceedings_publisher_place', models.CharField(blank=True, help_text='Mesto izdavanja zbornika', max_length=255, verbose_name='Mesto izdavanja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_issues', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='publications.publication', verbose_name='Publikacija')),
            ],
            options={
                'verbose_name': 'Izdanje',
                'verbose_name_plural': 'Izdanja',
                'ordering': ['-year', '-volume', '-issue_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('publication', 'volume', 'issue_number'), name='unique_issue_per_publication')],
            },
        ),
    ]
