# Generated by Django 5.2.10 on 2026-02-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='crossref_xml',
            field=models.TextField(blank=True, help_text='Generisani Crossref XML sadržaj', verbose_name='Crossref XML'),
        ),
        migrations.AddField(
            model_name='issue',
            name='xml_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='XML generisan'),
        ),
        migrations.AddField(
            model_name='issue',
            name='xml_generation_status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('generating', 'Generiše se'), ('completed', 'Završeno'), ('failed', 'Neuspešno')], default='pending', max_length=20, verbose_name='Status generisanja'),
        ),
    ]
