# Generated by Django 5.2.10 on 2026-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_add_crossref_xml_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='xsd_errors',
            field=models.JSONField(blank=True, default=list, help_text='Lista grešaka XSD validacije', verbose_name='XSD greške'),
        ),
        migrations.AddField(
            model_name='issue',
            name='xsd_valid',
            field=models.BooleanField(blank=True, help_text='Da li je XML validan prema Crossref XSD shemi', null=True, verbose_name='XSD validan'),
        ),
        migrations.AddField(
            model_name='issue',
            name='xsd_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='XSD validiran'),
        ),
    ]
