# Generated by Django 5.2.10 on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_add_xsd_validation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='crossref_deposited_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Datum i vreme kada je XML deponovan na Crossref',
                null=True,
                verbose_name='Crossref deponovano',
            ),
        ),
        migrations.AddField(
            model_name='issue',
            name='crossref_deposited_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='crossref_deposits',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Deponovao',
            ),
        ),
    ]
