# Generated by Django 5.2.10 on 2026-03-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_replace_publication_date_with_month_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='doi_suffix',
            field=models.CharField(blank=True, help_text='DOI sufiks za izdanje (opciono). Koristi se za registraciju DOI-ja na nivou izdanja.', max_length=255, verbose_name='DOI sufiks'),
        ),
        migrations.AddField(
            model_name='issue',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF fajl cele publikacije', null=True, upload_to='issues/pdfs/', verbose_name='PDF fajl'),
        ),
        migrations.AddField(
            model_name='issue',
            name='pdf_original_filename',
            field=models.CharField(blank=True, help_text='Originalno ime PDF fajla', max_length=500, verbose_name='Originalno ime PDF fajla'),
        ),
    ]
