# Generated by Django 5.2.10 on 2026-01-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositor_name', models.CharField(blank=True, help_text="Naziv organizacije koja salje XML na Crossref (npr. 'Grma')", max_length=255, verbose_name='Naziv deponenta')),
                ('depositor_email', models.EmailField(blank=True, help_text='Email za Crossref notifikacije o statusu deposit-a', max_length=254, verbose_name='Email deponenta')),
            ],
            options={
                'verbose_name': 'Podesavanja portala',
                'verbose_name_plural': 'Podesavanja portala',
            },
        ),
    ]
