# Generated by Django 5.2.10 on 2026-03-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_site_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Podešavanja portala', 'verbose_name_plural': 'Podešavanja portala'},
        ),
    ]
