# Generated by Django 5.2.10 on 2026-03-14 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GdprRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email podnosioca')),
                ('request_type', models.CharField(choices=[('ACCESS', 'Pristup podacima'), ('DELETION', 'Brisanje podataka')], max_length=20, verbose_name='Tip zahteva')),
                ('status', models.CharField(choices=[('PENDING', 'Na čekanju'), ('PROCESSING', 'U obradi'), ('COMPLETED', 'Završeno'), ('CANCELLED', 'Otkazano')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('received_date', models.DateField(verbose_name='Datum prijema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Obrađeno')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Završeno')),
                ('grace_period_end', models.DateField(blank=True, null=True, verbose_name='Kraj grace perioda')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Razlog otkazivanja')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_requests_processed', to=settings.AUTH_USER_MODEL, verbose_name='Obradio')),
            ],
            options={
                'verbose_name': 'GDPR zahtev',
                'verbose_name_plural': 'GDPR zahtevi',
                'ordering': ['-created_at'],
            },
        ),
    ]
