# Generated by Django 5.2.10 on 2026-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monographs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monograph',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='monographs/pdfs/', verbose_name='PDF fajl'),
        ),
        migrations.AddField(
            model_name='monograph',
            name='pdf_original_filename',
            field=models.CharField(blank=True, max_length=500, verbose_name='Originalni naziv fajla'),
        ),
        migrations.AddField(
            model_name='monograph',
            name='pdf_status',
            field=models.CharField(choices=[('none', 'Nema PDF-a'), ('uploading', 'Otpremanje'), ('scanning', 'Skeniranje'), ('clean', 'Čist'), ('infected', 'Inficiran'), ('scan_failed', 'Skeniranje neuspešno')], default='none', max_length=20, verbose_name='Status PDF-a'),
        ),
        migrations.AddField(
            model_name='monographchapter',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='monographs/chapter_pdfs/', verbose_name='PDF fajl'),
        ),
        migrations.AddField(
            model_name='monographchapter',
            name='pdf_original_filename',
            field=models.CharField(blank=True, max_length=500, verbose_name='Originalni naziv fajla'),
        ),
        migrations.AddField(
            model_name='monographchapter',
            name='pdf_status',
            field=models.CharField(choices=[('none', 'Nema PDF-a'), ('uploading', 'Otpremanje'), ('scanning', 'Skeniranje'), ('clean', 'Čist'), ('infected', 'Inficiran'), ('scan_failed', 'Skeniranje neuspešno')], default='none', max_length=20, verbose_name='Status PDF-a'),
        ),
    ]
