# Generated by Django 5.2.10 on 2026-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monographs', '0002_monograph_pdf_file_monograph_pdf_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monograph',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Naslovna slika monografije (JPG, PNG, max 2MB)', null=True, upload_to='monographs/covers/', verbose_name='Naslovna slika'),
        ),
    ]
