# Generated by Django 5.2.10 on 2026-01-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_extend_publisher_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Izdavač', 'verbose_name_plural': 'Izdavači'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, help_text='Opis izdavača', verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo izdavača (JPG, PNG, SVG, max 2MB)', null=True, upload_to='publishers/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Naziv izdavača', max_length=255, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, help_text='URL web sajta izdavača', verbose_name='Web sajt'),
        ),
    ]
