# Generated by Django 5.2.10 on 2026-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_alter_publisher_options_alter_publisher_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='depositor_email',
            field=models.EmailField(blank=True, help_text='Email adresa na koju Crossref šalje submission log', max_length=254, verbose_name='Depositor Email'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='depositor_name',
            field=models.CharField(blank=True, help_text='Naziv organizacije ili osobe koja šalje XML na Crossref', max_length=255, verbose_name='Depositor Name'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='registrant',
            field=models.CharField(blank=True, help_text='Naziv organizacije registranta', max_length=255, verbose_name='Registrant'),
        ),
    ]
