# Generated by Django 5.2.10 on 2026-01-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0004_add_crossref_depositor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='depositor_email',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='depositor_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='registrant',
        ),
    ]
