# Generated by Django 5.2.10 on 2026-03-15 15:17

import django.db.models.deletion
import doi_portal.publishers.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_alter_publisher_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='crossref_password',
            field=doi_portal.publishers.fields.EncryptedCharField(blank=True, help_text='Lozinka za Crossref API (enkriptovana u bazi)', max_length=255, verbose_name='Crossref lozinka'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='crossref_username',
            field=models.CharField(blank=True, help_text='Korisničko ime za Crossref API', max_length=100, verbose_name='Crossref korisničko ime'),
        ),
        migrations.CreateModel(
            name='PublisherContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=100, verbose_name='Prezime')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('role', models.CharField(blank=True, help_text='npr. direktor, urednik, kontakt za Crossref', max_length=100, verbose_name='Funkcija')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='publishers.publisher')),
            ],
            options={
                'verbose_name': 'Kontakt osoba',
                'verbose_name_plural': 'Kontakt osobe',
                'ordering': ['order', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PublisherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Tekst napomene')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Izmenjeno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='publishers.publisher')),
            ],
            options={
                'verbose_name': 'Napomena',
                'verbose_name_plural': 'Napomene',
                'ordering': ['-created_at'],
            },
        ),
    ]
