"""Create activity_logs table

Revision ID: b9bada2cfba6
Revises: 38659bec4f1b
Create Date: 2025-08-29 11:53:53.156605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bada2cfba6'
down_revision = '38659bec4f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('idx_activity_action', ['action'], unique=False)
        batch_op.create_index('idx_activity_composite', ['user_id', 'action', 'created_at'], unique=False)
        batch_op.create_index('idx_activity_created', ['created_at'], unique=False)
        batch_op.create_index('idx_activity_member', ['member_id'], unique=False)
        batch_op.create_index('idx_activity_publication', ['publication_id'], unique=False)
        batch_op.create_index('idx_activity_user', ['user_id'], unique=False)

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index('idx_book_isbn', ['isbn'], unique=False)
        batch_op.create_index('idx_journal_issn', ['journal_issn'], unique=False)
        batch_op.create_index('idx_publication_member_type', ['member_id', 'publication_type', 'is_active'], unique=False)
        batch_op.create_index('idx_publication_title', ['title'], unique=False)
        batch_op.create_index('idx_publication_type', ['publication_type'], unique=False)
        batch_op.create_index('idx_series_issn', ['series_issn'], unique=False)
        batch_op.create_index('idx_set_isbn', ['set_isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_publication_type'), ['publication_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_title'))
        batch_op.drop_index(batch_op.f('ix_publications_publication_type'))
        batch_op.drop_index(batch_op.f('ix_publications_member_id'))
        batch_op.drop_index(batch_op.f('ix_publications_is_active'))
        batch_op.drop_index('idx_set_isbn')
        batch_op.drop_index('idx_series_issn')
        batch_op.drop_index('idx_publication_type')
        batch_op.drop_index('idx_publication_title')
        batch_op.drop_index('idx_publication_member_type')
        batch_op.drop_index('idx_journal_issn')
        batch_op.drop_index('idx_book_isbn')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_user')
        batch_op.drop_index('idx_activity_publication')
        batch_op.drop_index('idx_activity_member')
        batch_op.drop_index('idx_activity_created')
        batch_op.drop_index('idx_activity_composite')
        batch_op.drop_index('idx_activity_action')

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
