"""Add Member and Publication models with Crossref metadata fields

Revision ID: e46f5136f401
Revises: seed_initial_sponsor
Create Date: 2025-08-25 23:21:17.494709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46f5136f401'
down_revision = 'seed_initial_sponsor'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('pib', sa.String(length=20), nullable=False),
    sa.Column('matični_broj', sa.String(length=20), nullable=False),
    sa.Column('jmbg_lk', sa.String(length=20), nullable=True),
    sa.Column('šifra_delatnosti', sa.String(length=10), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('osoba_za_kontakt', sa.String(length=100), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('naziv_banke', sa.String(length=100), nullable=False),
    sa.Column('swift_bic', sa.String(length=11), nullable=False),
    sa.Column('pdv_status', sa.String(length=50), nullable=False),
    sa.Column('država_obveznika', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('idx_member_email', ['contact_email'], unique=False)
        batch_op.create_index('idx_member_name', ['name'], unique=False)
        batch_op.create_index('idx_member_sponsor_active', ['sponsor_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_sponsor_id'), ['sponsor_id'], unique=False)

    op.create_table('publications',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOURNAL', 'BOOK', 'MONOGRAPH', name='publicationtype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('original_language_title', sa.String(length=500), nullable=True),
    sa.Column('issn_isbn', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('publisher_place', sa.String(length=200), nullable=True),
    sa.Column('journal_abbreviated_title', sa.String(length=200), nullable=True),
    sa.Column('journal_coden', sa.String(length=10), nullable=True),
    sa.Column('book_type', sa.String(length=50), nullable=True),
    sa.Column('edition_number', sa.Integer(), nullable=True),
    sa.Column('series_title', sa.String(length=200), nullable=True),
    sa.Column('series_subtitle', sa.String(length=200), nullable=True),
    sa.Column('series_issn_print', sa.String(length=20), nullable=True),
    sa.Column('series_issn_electronic', sa.String(length=20), nullable=True),
    sa.Column('series_coden', sa.String(length=10), nullable=True),
    sa.Column('series_number', sa.String(length=50), nullable=True),
    sa.Column('set_title', sa.String(length=200), nullable=True),
    sa.Column('set_subtitle', sa.String(length=200), nullable=True),
    sa.Column('set_isbn_print', sa.String(length=20), nullable=True),
    sa.Column('set_isbn_electronic', sa.String(length=20), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('volume_number', sa.String(length=50), nullable=True),
    sa.Column('isbn_print', sa.String(length=20), nullable=True),
    sa.Column('isbn_electronic', sa.String(length=20), nullable=True),
    sa.Column('issn_print', sa.String(length=20), nullable=True),
    sa.Column('issn_electronic', sa.String(length=20), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_month', sa.Integer(), nullable=True),
    sa.Column('publication_day', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('publication_doi', sa.String(length=100), nullable=True),
    sa.Column('resource_url', sa.String(length=500), nullable=True),
    sa.Column('crossref_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index('idx_publication_issn_isbn', ['issn_isbn'], unique=False)
        batch_op.create_index('idx_publication_member_type', ['member_id', 'type', 'is_active'], unique=False)
        batch_op.create_index('idx_publication_title', ['title'], unique=False)
        batch_op.create_index('idx_publication_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_member_id'))
        batch_op.drop_index(batch_op.f('ix_publications_is_active'))
        batch_op.drop_index('idx_publication_type')
        batch_op.drop_index('idx_publication_title')
        batch_op.drop_index('idx_publication_member_type')
        batch_op.drop_index('idx_publication_issn_isbn')

    op.drop_table('publications')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_sponsor_id'))
        batch_op.drop_index(batch_op.f('ix_members_is_active'))
        batch_op.drop_index('idx_member_sponsor_active')
        batch_op.drop_index('idx_member_name')
        batch_op.drop_index('idx_member_email')

    op.drop_table('members')
    # ### end Alembic commands ###
