"""Initial migration: Create Sponsor and User models

Revision ID: ec5536d1a051
Revises: 
Create Date: 2025-08-18 22:40:08.022550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5536d1a051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('crossref_member_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_crossref_member_id'), ['crossref_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_sponsors_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='user_roles'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_is_active'))
        batch_op.drop_index(batch_op.f('ix_sponsors_email'))
        batch_op.drop_index(batch_op.f('ix_sponsors_crossref_member_id'))

    op.drop_table('sponsors')
    # ### end Alembic commands ###
