volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}
  production_redis_data: {}
  production_clamav_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: doi_portal_production_django
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - production_django_media:/app/doi_portal/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: doi_portal_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: doi_portal_production_traefik
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:7.2
    restart: unless-stopped
    volumes:
      - production_redis_data:/data

  clamav:
    image: clamav/clamav:latest
    restart: unless-stopped
    volumes:
      - production_clamav_data:/var/lib/clamav

  celeryworker:
    <<: *django
    image: doi_portal_production_celeryworker
    depends_on:
      - postgres
      - redis
      - clamav
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: doi_portal_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: doi_portal_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
