# Generated by Django 5.2.10 on 2026-02-03 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0003_add_xsd_validation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossrefExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_content', models.TextField(help_text='Snapshot XML sadržaja u trenutku eksporta', verbose_name='XML sadržaj')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='Eksportovano')),
                ('filename', models.CharField(max_length=255, verbose_name='Ime fajla')),
                ('xsd_valid_at_export', models.BooleanField(null=True, verbose_name='XSD validan pri eksportu')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossref_exports', to=settings.AUTH_USER_MODEL, verbose_name='Eksportovao')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossref_exports', to='issues.issue', verbose_name='Izdanje')),
            ],
            options={
                'verbose_name': 'Crossref eksport',
                'verbose_name_plural': 'Crossref eksporti',
                'ordering': ['-exported_at'],
            },
        ),
    ]
