# Generated by Django 5.2.10 on 2026-03-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('crossref', '0001_crossrefexport'),
        ('issues', '0007_add_doi_suffix_pdf_to_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crossrefexport',
            name='component_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossref_exports', to='components.componentgroup', verbose_name='Grupa komponenti'),
        ),
        migrations.AddField(
            model_name='crossrefexport',
            name='export_type',
            field=models.CharField(choices=[('ISSUE', 'Izdanje'), ('COMPONENT_GROUP', 'Grupa komponenti')], default='ISSUE', max_length=20, verbose_name='Tip eksporta'),
        ),
        migrations.AlterField(
            model_name='crossrefexport',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossref_exports', to='issues.issue', verbose_name='Izdanje'),
        ),
        migrations.AddConstraint(
            model_name='crossrefexport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component_group__isnull', True), ('export_type', 'ISSUE'), ('issue__isnull', False)), models.Q(('component_group__isnull', False), ('export_type', 'COMPONENT_GROUP'), ('issue__isnull', True)), _connector='OR'), name='crossref_export_exactly_one_source'),
        ),
    ]
