# Generated by Django 5.2.10 on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossref', '0002_crossrefexport_component_group_and_more'),
        ('monographs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossrefexport',
            name='monograph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossref_exports', to='monographs.monograph', verbose_name='Monografija'),
        ),
        migrations.AlterField(
            model_name='crossrefexport',
            name='export_type',
            field=models.CharField(choices=[('ISSUE', 'Izdanje'), ('COMPONENT_GROUP', 'Grupa komponenti'), ('MONOGRAPH', 'Monografija')], default='ISSUE', max_length=20, verbose_name='Tip eksporta'),
        ),
        migrations.RemoveConstraint(
            model_name='crossrefexport',
            name='crossref_export_exactly_one_source',
        ),
        migrations.AddConstraint(
            model_name='crossrefexport',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('component_group__isnull', True), ('export_type', 'ISSUE'), ('issue__isnull', False), ('monograph__isnull', True)),
                    models.Q(('component_group__isnull', False), ('export_type', 'COMPONENT_GROUP'), ('issue__isnull', True), ('monograph__isnull', True)),
                    models.Q(('component_group__isnull', True), ('export_type', 'MONOGRAPH'), ('issue__isnull', True), ('monograph__isnull', False)),
                    _connector='OR',
                ),
                name='crossref_export_exactly_one_source',
            ),
        ),
    ]
