# Generated by Django 5.2.10 on 2026-01-31 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Naslov')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Podnaslov')),
                ('abstract', models.TextField(blank=True, verbose_name='Apstrakt')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Ključne reči')),
                ('doi_suffix', models.CharField(max_length=100, verbose_name='DOI sufiks')),
                ('first_page', models.CharField(blank=True, max_length=20, verbose_name='Prva stranica')),
                ('last_page', models.CharField(blank=True, max_length=20, verbose_name='Poslednja stranica')),
                ('article_number', models.CharField(blank=True, help_text='Za online-only članke', max_length=50, verbose_name='Broj članka')),
                ('language', models.CharField(default='sr', max_length=10, verbose_name='Jezik')),
                ('publication_type', models.CharField(choices=[('full_text', 'Puni tekst'), ('abstract_only', 'Samo apstrakt'), ('bibliographic_record', 'Bibliografski zapis')], default='full_text', max_length=30, verbose_name='Tip sadržaja')),
                ('license_url', models.URLField(blank=True, verbose_name='URL licence')),
                ('license_applies_to', models.CharField(blank=True, choices=[('vor', 'Verzija zapisa (VoR)'), ('am', 'Prihvaćeni rukopis (AM)'), ('tdm', 'Rudarenje teksta (TDM)')], max_length=10, verbose_name='Licenca se odnosi na')),
                ('free_to_read', models.BooleanField(default=False, verbose_name='Slobodan pristup')),
                ('free_to_read_start_date', models.DateField(blank=True, null=True, verbose_name='Datum početka slobodnog pristupa')),
                ('pdf_file', models.FileField(blank=True, upload_to='articles/pdfs/', verbose_name='PDF fajl')),
                ('status', models.CharField(choices=[('DRAFT', 'Nacrt'), ('REVIEW', 'Na pregledu'), ('READY', 'Spremno za objavu'), ('PUBLISHED', 'Objavljeno'), ('WITHDRAWN', 'Povučeno')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_articles', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='issues.issue', verbose_name='Izdanje')),
            ],
            options={
                'verbose_name': 'Članak',
                'verbose_name_plural': 'Članci',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('issue', 'doi_suffix'), name='unique_article_doi_suffix_per_issue')],
            },
        ),
    ]
