# Generated by Django 5.2.10 on 2026-01-31 15:42

import django.db.models.deletion
import doi_portal.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(blank=True, max_length=255, verbose_name='Ime')),
                ('surname', models.CharField(max_length=255, verbose_name='Prezime')),
                ('suffix', models.CharField(blank=True, help_text='npr. Jr., III', max_length=50, verbose_name='Sufiks')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('orcid', models.CharField(blank=True, help_text='Format: 0000-0000-0000-000X', max_length=19, validators=[doi_portal.articles.validators.validate_orcid], verbose_name='ORCID')),
                ('orcid_authenticated', models.BooleanField(default=False, verbose_name='ORCID autentifikovan')),
                ('sequence', models.CharField(choices=[('first', 'Glavni (first)'), ('additional', 'Ostali (additional)')], default='additional', max_length=20, verbose_name='Redosled (Crossref)')),
                ('contributor_role', models.CharField(choices=[('author', 'Autor'), ('editor', 'Urednik'), ('chair', 'Predsedavajući'), ('translator', 'Prevodilac'), ('reviewer', 'Recenzent')], default='author', max_length=20, verbose_name='Uloga kontributora')),
                ('is_corresponding', models.BooleanField(default=False, verbose_name='Korespondentan autor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redni broj')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='articles.article', verbose_name='Članak')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autori',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=500, verbose_name='Naziv institucije')),
                ('institution_ror_id', models.URLField(blank=True, help_text='https://ror.org/...', verbose_name='ROR ID')),
                ('department', models.CharField(blank=True, max_length=500, verbose_name='Departman')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redni broj')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='articles.author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Afilijacija',
                'verbose_name_plural': 'Afilijacije',
                'ordering': ['order'],
            },
        ),
    ]
