# Generated by Django 5.2.10 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_author_affiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="pdf_status",
            field=models.CharField(
                choices=[
                    ("none", "Nema PDF-a"),
                    ("uploading", "Otpremanje"),
                    ("scanning", "Skeniranje"),
                    ("clean", "Čist"),
                    ("infected", "Inficiran"),
                    ("scan_failed", "Skeniranje neuspešno"),
                ],
                default="none",
                max_length=20,
                verbose_name="PDF status",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pdf_original_filename",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Originalni naziv fajla",
            ),
        ),
    ]
