# Generated by Django 5.2.10 on 2026-02-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_pdf_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Poslat na pregled'),
        ),
        migrations.AddField(
            model_name='article',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_articles', to=settings.AUTH_USER_MODEL, verbose_name='Poslao na pregled'),
        ),
    ]
