# Generated by Django 5.2.10 on 2026-02-01 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_add_submitted_by_submitted_at_to_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vraćeno na doradu'),
        ),
        migrations.AddField(
            model_name='article',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_articles', to=settings.AUTH_USER_MODEL, verbose_name='Vratio na doradu'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odobreno'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='Odobrio'),
        ),
        migrations.AddField(
            model_name='article',
            name='revision_comment',
            field=models.TextField(blank=True, help_text='Komentar urednika pri vraćanju članka na doradu.', verbose_name='Komentar za doradu'),
        ),
    ]
