# Generated by Django 5.2.10 on 2026-02-01 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_add_review_tracking_fields_to_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Objavljeno'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to=settings.AUTH_USER_MODEL, verbose_name='Objavio'),
        ),
        migrations.AddField(
            model_name='article',
            name='withdrawal_reason',
            field=models.TextField(blank=True, help_text='Razlog povlačenja objavljenog članka.', verbose_name='Razlog povlačenja'),
        ),
        migrations.AddField(
            model_name='article',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Povučeno'),
        ),
        migrations.AddField(
            model_name='article',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_articles', to=settings.AUTH_USER_MODEL, verbose_name='Povukao'),
        ),
    ]
