# Generated by Django 5.2.10 on 2026-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_add_publish_withdraw_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_landing_url',
            field=models.URLField(blank=True, help_text='URL stranice članka na sajtu izdavača', max_length=500, verbose_name='Eksterna landing stranica'),
        ),
        migrations.AddField(
            model_name='article',
            name='external_pdf_url',
            field=models.URLField(blank=True, help_text='URL PDF fajla na sajtu izdavača (opciono)', max_length=500, verbose_name='Eksterni PDF URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='use_external_resource',
            field=models.BooleanField(default=False, help_text='Ako je uključeno, DOI će pokazivati na sajt izdavača umesto na portal.', verbose_name='Koristi eksterni URL za DOI'),
        ),
    ]
