# Generated by Django 5.2.10 on 2026-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_add_external_resource_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='original_language_subtitle',
            field=models.CharField(blank=True, help_text='Podnaslov na jeziku članka (opciono)', max_length=500, verbose_name='Podnaslov na originalnom jeziku'),
        ),
        migrations.AddField(
            model_name='article',
            name='original_language_title',
            field=models.CharField(blank=True, help_text='Naslov na jeziku članka (opciono)', max_length=500, verbose_name='Naslov na originalnom jeziku'),
        ),
        migrations.AddField(
            model_name='article',
            name='original_language_title_language',
            field=models.CharField(blank=True, help_text='ISO 639 jezički kod za originalni naslov (npr. sr, en)', max_length=10, verbose_name='Jezik originalnog naslova'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(blank=True, help_text='Alternativa za stranice kod članaka bez paginacije (npr. e12345)', max_length=50, verbose_name='Broj članka'),
        ),
    ]
