# Generated by Django 5.2.10 on 2026-03-14 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_add_affiliation_location_and_funding_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'default_manager_name': 'objects', 'ordering': ['order'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autori'},
        ),
        migrations.AddField(
            model_name='author',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja'),
        ),
        migrations.AddField(
            model_name='author',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Obrisano'),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao'),
        ),
    ]
