# Generated by Django 5.2.10 on 2026-01-26 22:08

import django.db.models.deletion
import doi_portal.publications.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0003_alter_publisher_options_alter_publisher_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Puni naslov publikacije', max_length=500, verbose_name='Naslov')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='Slug')),
                ('publication_type', models.CharField(choices=[('JOURNAL', 'Časopis'), ('CONFERENCE', 'Zbornik'), ('BOOK', 'Monografija'), ('OTHER', 'Ostalo')], default='JOURNAL', max_length=20, verbose_name='Tip publikacije')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/', verbose_name='Naslovna slika')),
                ('language', models.CharField(default='sr', help_text="ISO 639-1 kod jezika (npr. 'sr', 'en')", max_length=10, verbose_name='Jezik')),
                ('subject_area', models.CharField(blank=True, max_length=255, verbose_name='Naučna oblast')),
                ('access_type', models.CharField(choices=[('OPEN', 'Otvoreni pristup'), ('RESTRICTED', 'Ograničeni pristup')], default='OPEN', max_length=20, verbose_name='Tip pristupa')),
                ('issn_print', models.CharField(blank=True, help_text='Format: ####-####', max_length=9, validators=[doi_portal.publications.validators.validate_issn], verbose_name='ISSN (štampano)')),
                ('issn_online', models.CharField(blank=True, help_text='Format: ####-####', max_length=9, validators=[doi_portal.publications.validators.validate_issn], verbose_name='ISSN (online)')),
                ('abbreviation', models.CharField(blank=True, help_text='ISO skraćenica časopisa', max_length=50, verbose_name='Skraćenica')),
                ('frequency', models.CharField(blank=True, help_text="npr. 'Kvartalno', 'Godišnje'", max_length=50, verbose_name='Učestalost izlaženja')),
                ('conference_name', models.CharField(blank=True, max_length=500, verbose_name='Naziv konferencije')),
                ('conference_acronym', models.CharField(blank=True, max_length=50, verbose_name='Akronim konferencije')),
                ('conference_location', models.CharField(blank=True, max_length=255, verbose_name='Lokacija konferencije')),
                ('conference_date', models.DateField(blank=True, null=True, verbose_name='Datum konferencije')),
                ('series_issn', models.CharField(blank=True, max_length=9, validators=[doi_portal.publications.validators.validate_issn], verbose_name='ISSN serije')),
                ('isbn_print', models.CharField(blank=True, help_text='Format: 978-X-XXXX-XXXX-X', max_length=17, validators=[doi_portal.publications.validators.validate_isbn], verbose_name='ISBN (štampano)')),
                ('isbn_online', models.CharField(blank=True, max_length=17, validators=[doi_portal.publications.validators.validate_isbn], verbose_name='ISBN (online)')),
                ('edition', models.CharField(blank=True, help_text="npr. '1. izdanje', '2. dopunjeno izdanje'", max_length=50, verbose_name='Izdanje')),
                ('series_title', models.CharField(blank=True, max_length=500, verbose_name='Naslov serije')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_publications', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publishers.publisher', verbose_name='Izdavač')),
            ],
            options={
                'verbose_name': 'Publikacija',
                'verbose_name_plural': 'Publikacije',
                'ordering': ['title'],
            },
        ),
    ]
