# Generated by Django 5.2.10 on 2026-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='conference_date_end',
            field=models.DateField(blank=True, help_text='Datum završetka konferencije', null=True, verbose_name='Conference End Date'),
        ),
        migrations.AddField(
            model_name='publication',
            name='conference_number',
            field=models.PositiveIntegerField(blank=True, help_text="Redni broj konferencije (npr. 5 za '5th Annual Conference')", null=True, verbose_name='Conference Number'),
        ),
    ]
