# Generated by Django 5.2.10 on 2026-01-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_add_conference_end_date_and_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='conference_date_end',
            field=models.DateField(blank=True, help_text='Datum završetka konferencije', null=True, verbose_name='Datum završetka konferencije'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference_number',
            field=models.PositiveIntegerField(blank=True, help_text="Redni broj konferencije (npr. 5 za '5. godišnja konferencija')", null=True, verbose_name='Broj konferencije'),
        ),
    ]
