# Generated by Django 5.2.10 on 2026-04-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='series_title',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('JOURNAL', 'Časopis'), ('CONFERENCE', 'Zbornik'), ('OTHER', 'Ostalo')], default='JOURNAL', max_length=20, verbose_name='Tip publikacije'),
        ),
    ]
