# Generated by Django 5.2.10 on 2026-03-20 21:22

import django.core.validators
import django.db.models.deletion
import doi_portal.articles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0007_publisher_crossref_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('parent_relation', models.CharField(default='isPartOf', help_text='Crossref parent_relation atribut', max_length=50, verbose_name='Relacija sa roditeljem')),
                ('title', models.CharField(blank=True, help_text='Naslov komponente (preporučeno)', max_length=500, verbose_name='Naslov')),
                ('description', models.TextField(blank=True, help_text='Crossref description element', verbose_name='Opis')),
                ('format_mime_type', models.CharField(blank=True, help_text='MIME tip fajla (npr. audio/mpeg, video/mp4, application/pdf)', max_length=100, verbose_name='MIME tip')),
                ('doi_suffix', models.CharField(help_text='Sufiks za DOI (kompletni DOI = publisher.doi_prefix + / + doi_suffix)', max_length=100, verbose_name='DOI sufiks')),
                ('resource_url', models.URLField(blank=True, help_text='Auto-generiše se ako je prazno', max_length=500, verbose_name='URL resursa')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Godina publikacije')),
                ('publication_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mesec publikacije')),
                ('publication_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dan publikacije')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
            ],
            options={
                'verbose_name': 'Komponenta',
                'verbose_name_plural': 'Komponente',
                'ordering': ['order', 'created_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ComponentContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('given_name', models.CharField(blank=True, max_length=255, verbose_name='Ime')),
                ('surname', models.CharField(max_length=255, verbose_name='Prezime')),
                ('suffix', models.CharField(blank=True, max_length=50, verbose_name='Sufiks')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('orcid', models.CharField(blank=True, max_length=19, validators=[doi_portal.articles.validators.validate_orcid], verbose_name='ORCID')),
                ('orcid_authenticated', models.BooleanField(default=False, verbose_name='ORCID autentifikovan')),
                ('sequence', models.CharField(choices=[('first', 'Glavni (first)'), ('additional', 'Ostali (additional)')], default='additional', max_length=20, verbose_name='Redosled')),
                ('contributor_role', models.CharField(choices=[('author', 'Autor'), ('editor', 'Urednik'), ('chair', 'Predsedavajući'), ('translator', 'Prevodilac'), ('reviewer', 'Recenzent')], default='author', max_length=20, verbose_name='Uloga')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='components.component', verbose_name='Komponenta')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
            ],
            options={
                'verbose_name': 'Kontributor komponente',
                'verbose_name_plural': 'Kontributori komponente',
                'ordering': ['order'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Obrisano')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vreme brisanja')),
                ('parent_doi', models.CharField(help_text='Puni DOI roditelja (npr. 10.66117/emce_zapisi.2026.1)', max_length=255, verbose_name='Parent DOI')),
                ('title', models.CharField(blank=True, help_text='Opcioni label za UI prikaz', max_length=500, verbose_name='Naslov')),
                ('crossref_xml', models.TextField(blank=True, verbose_name='Crossref XML')),
                ('xml_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='XML generisan')),
                ('xml_generation_status', models.CharField(choices=[('pending', 'Na čekanju'), ('generating', 'Generisanje'), ('completed', 'Završeno'), ('failed', 'Neuspešno')], default='pending', max_length=20, verbose_name='Status generisanja')),
                ('xsd_valid', models.BooleanField(blank=True, null=True, verbose_name='XSD validan')),
                ('xsd_errors', models.JSONField(blank=True, default=list, verbose_name='XSD greške')),
                ('xsd_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='XSD validiran')),
                ('crossref_deposited_at', models.DateTimeField(blank=True, null=True, verbose_name='Deponovano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('crossref_deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Deponovao')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Obrisao')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_groups', to='publishers.publisher', verbose_name='Izdavač')),
            ],
            options={
                'verbose_name': 'Grupa komponenti',
                'verbose_name_plural': 'Grupe komponenti',
                'ordering': ['-created_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='component_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.componentgroup', verbose_name='Grupa komponenti'),
        ),
        migrations.AddConstraint(
            model_name='componentgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('publisher', 'parent_doi'), name='unique_component_group_parent_doi_per_publisher'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('component_group', 'doi_suffix'), name='unique_component_doi_suffix_per_group'),
        ),
    ]
